version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: myTailwindJhipster
      POSTGRES_USER: myTailwindJhipster
      POSTGRES_PASSWORD: myTailwindJhipster
    ports:
      - '5432:5432'
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U myTailwindJhipster']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata-dev:
    driver: local
